apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asset-service-2
  title: Asset Service 2.0
  description: Asset-Service is a collection of assets that are linked with each other which forms a special hierarchy.
  tags:
    - java
    - data
  annotations:
    github.com/project-slug: bh-ent-tech/arion-fs-assets-2.0
    backstage.io/techdocs-ref: dir:.
  links:
   - url: https://github.com/bh-ent-tech/arion-fs-assets-2.0
     title: GitHub Repo
     icon: github
spec:
  type: service
  lifecycle: production
  owner: team-a
  providesApis:
    - artist-api
    
