site_name: 'example-docs'

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Performance Specifications: performance-specifications.md
  - Release Information: release-information.md

plugins:
  - techdocs-core
