site_name: 'Asset Service 2.0'
site_description: 'Main documentation for Asset Service features and platform APIs'
repo_url: https://github.com/bh-ent-tech/arion-fs-assets-2.0
edit_uri: edit/master/docs

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Performance Specifications: performance-specifications.md
  - Release Information: release-information.md

plugins:
  - techdocs-core
  - git-revision-date-localized
